#pragma once

#include "../Config.h"

#include <string>


namespace toxic
{
	class TOXIC_API Convert
	{
	public:
		static bool ToBool(char val);
		static bool ToBool(unsigned char val);
		static bool ToBool(short val);
		static bool ToBool(unsigned short val);
		static bool ToBool(int val);
		static bool ToBool(unsigned int val);
		static bool ToBool(long val);
		static bool ToBool(unsigned long val);
		static bool ToBool(long long val);
		static bool ToBool(unsigned long long val);
		static bool ToBool(float val);
		static bool ToBool(double val);
		static bool ToBool(long double val);
		static bool ToBool(const std::string& val);
		static char ToChar(bool val);
		static char ToChar(short val);
		static char ToChar(unsigned short val);
		static char ToChar(int val);
		static char ToChar(unsigned int val);
		static char ToChar(long val);
		static char ToChar(unsigned long val);
		static char ToChar(long long val);
		static char ToChar(unsigned long long val);
		static char ToChar(const std::string& val);
		static short ToShort(bool val);
		static short ToShort(char val);
		static short ToShort(unsigned char val);
		static short ToShort(unsigned short val);
		static short ToShort(int val);
		static short ToShort(unsigned int val);
		static short ToShort(long val);
		static short ToShort(unsigned long val);
		static short ToShort(long long val);
		static short ToShort(unsigned long long val);
		static short ToShort(float val);
		static short ToShort(double val);
		static short ToShort(long double val);
		static short ToShort(const std::string& val);
		static int ToInt(bool val);
		static int ToInt(char val);
		static int ToInt(unsigned char val);
		static int ToInt(short val);
		static int ToInt(unsigned short val);
		static int ToInt(unsigned int val);
		static int ToInt(long val);
		static int ToInt(unsigned long val);
		static int ToInt(long long val);
		static int ToInt(unsigned long long val);
		static int ToInt(float val);
		static int ToInt(double val);
		static int ToInt(long double val);
		static int ToInt(const std::string& val);
		static long ToLong(bool val);
		static long ToLong(char val);
		static long ToLong(unsigned char val);
		static long ToLong(short val);
		static long ToLong(unsigned short val);
		static long ToLong(int val);
		static long ToLong(unsigned int val);
		static long ToLong(unsigned long val);
		static long ToLong(long long val);
		static long ToLong(unsigned long long val);
		static long ToLong(float val);
		static long ToLong(double val);
		static long ToLong(long double val);
		static long ToLong(const std::string& val);
		static long long ToLongLong(bool val);
		static long long ToLongLong(char val);
		static long long ToLongLong(unsigned char val);
		static long long ToLongLong(short val);
		static long long ToLongLong(unsigned short val);
		static long long ToLongLong(int val);
		static long long ToLongLong(unsigned int val);
		static long long ToLongLong(long val);
		static long long ToLongLong(unsigned long val);
		static long long ToLongLong(unsigned long long val);
		static long long ToLongLong(float val);
		static long long ToLongLong(double val);
		static long long ToLongLong(long double val);
		static long long ToLongLong(const std::string& val);
		static float ToFloat(bool val);
		static float ToFloat(char val);
		static float ToFloat(unsigned char val);
		static float ToFloat(short val);
		static float ToFloat(unsigned short val);
		static float ToFloat(int val);
		static float ToFloat(unsigned int val);
		static float ToFloat(long val);
		static float ToFloat(unsigned long val);
		static float ToFloat(long long val);
		static float ToFloat(unsigned long long val);
		static float ToFloat(double val);
		static float ToFloat(long double val);
		static float ToFloat(const std::string& val);
		static double ToDouble(bool val);
		static double ToDouble(char val);
		static double ToDouble(unsigned char val);
		static double ToDouble(short val);
		static double ToDouble(unsigned short val);
		static double ToDouble(int val);
		static double ToDouble(unsigned int val);
		static double ToDouble(long val);
		static double ToDouble(unsigned long val);
		static double ToDouble(long long val);
		static double ToDouble(unsigned long long val);
		static double ToDouble(float val);
		static double ToDouble(long double val);
		static double ToDouble(const std::string& val);
		static long double ToLongDouble(bool val);
		static long double ToLongDouble(char val);
		static long double ToLongDouble(unsigned char val);
		static long double ToLongDouble(short val);
		static long double ToLongDouble(unsigned short val);
		static long double ToLongDouble(int val);
		static long double ToLongDouble(unsigned int val);
		static long double ToLongDouble(long val);
		static long double ToLongDouble(unsigned long val);
		static long double ToLongDouble(long long val);
		static long double ToLongDouble(unsigned long long val);
		static long double ToLongDouble(float val);
		static long double ToLongDouble(double val);
		static long double ToLongDouble(const std::string& val);
		static std::string ToString(char val);
		static std::string ToString(unsigned char val);
		static std::string ToString(short val);
		static std::string ToString(unsigned short val);
		static std::string ToString(int val);
		static std::string ToString(unsigned int val);
		static std::string ToString(long val);
		static std::string ToString(unsigned long val);
		static std::string ToString(long long val);
		static std::string ToString(unsigned long long val);
		static std::string ToString(float val);
		static std::string ToString(double val);
		static std::string ToString(long double val);
		static std::string ToString(const char* val);
		static std::string ToString(const std::wstring& val);
		static std::wstring ToWideString(char val);
		static std::wstring ToWideString(unsigned char val);
		static std::wstring ToWideString(short val);
		static std::wstring ToWideString(unsigned short val);
		static std::wstring ToWideString(int val);
		static std::wstring ToWideString(unsigned int val);
		static std::wstring ToWideString(long val);
		static std::wstring ToWideString(unsigned long val);
		static std::wstring ToWideString(long long val);
		static std::wstring ToWideString(unsigned long long val);
		static std::wstring ToWideString(float val);
		static std::wstring ToWideString(double val);
		static std::wstring ToWideString(long double val);
		static std::wstring ToWideString(const std::string& val);
	};
}
